<?php
/* File autogenerated by SugarCRM in ActivitesRelationship.php / buildSidecarDashletMeta */

$coreDefs = MetaDataFiles::loadSingleClientMetadata('view','attachments');
$coreDefs['dashlets'][0]['filter']['module'] = array('jbs_Jobs');
$coreDefs['dashlets'][0]['config']['link'] = 'jbs_jobs_activities_1_notes';
$coreDefs['dashlets'][0]['preview']['link'] = 'jbs_jobs_activities_1_notes';
$viewdefs['jbs_Jobs']['base']['view']['attachments'] = $coreDefs;
