<?php
/* File autogenerated by SugarCRM in ActivitesRelationship.php / buildSidecarDashletMeta */

$coreDefs = MetaDataFiles::loadSingleClientMetadata('view','active-tasks');
$coreDefs['dashlets'][0]['filter']['module'] = array('con_Contractors');
$coreDefs['custom_toolbar']['buttons'][0]['buttons'][0]['params']['link'] = 'con_contractors_activities_1_tasks';
$coreDefs['tabs'][0]['link'] = 'con_contractors_activities_1_tasks';
$coreDefs['tabs'][1]['link'] = 'con_contractors_activities_1_tasks';
$viewdefs['con_Contractors']['base']['view']['active-tasks'] = $coreDefs;
