/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({titleSelectedValues:'',titleViewNameTitle:'',titleMessage:'',toggleTitleTpl:{},isForecastSetup:undefined,tpStartDate:undefined,fiscalYearField:undefined,initialize:function(options){this.isForecastSetup=app.metadata.getModule('Forecasts','config').is_setup;if(!this.isForecastSetup){_.each(_.first(options.meta.panels).fields,function(field){if(field.name=='timeperiod_start_date'){field.click_to_edit=true;}},this);}
this._super('initialize',[options]);this.titleViewNameTitle=app.lang.get('LBL_FORECASTS_CONFIG_TITLE_TIMEPERIODS','Forecasts');this.titleMessage=app.lang.get('LBL_FORECASTS_CONFIG_TITLE_MESSAGE_TIMEPERIODS','Forecasts');this.toggleTitleTpl=app.template.getView('forecastsConfigHelpers.toggleTitle','Forecasts');},checkFiscalYearField:function(){if(this.tpStartDate.month()!==0||(this.tpStartDate.month()===0&&this.tpStartDate.date()!==1)){this.addFiscalYearField();}else if(this.fiscalYearField){this.model.set({timeperiod_fiscal_year:null});this.removeFiscalYearField();}},bindDataChange:function(){if(this.model){this.model.once('change',function(model){if(_.isUndefined(model)){model=this.model;}},this);this.model.on('change:timeperiod_start_date',function(model){this.tpStartDate=app.date(model.get('timeperiod_start_date'));this.checkFiscalYearField();this.titleSelectedValues=this.tpStartDate.formatUser(true);this.updateTitle();},this);}},addFiscalYearField:function(){if(!this.fiscalYearField){this.model.set({timeperiod_fiscal_year:'current_year'});var $el=this.$('#timeperiod_start_date_subfield');if($el){var fiscalYearFieldMeta=_.find(this.options.meta.panels[0].fields,function(field){return field.name=='timeperiod_fiscal_year';});fiscalYearFieldMeta=this.updateFieldMetadata(fiscalYearFieldMeta);var fieldSettings={view:this,def:fiscalYearFieldMeta,viewName:'edit',context:this.context,module:this.module,model:this.model,meta:app.metadata.getField('enum')};this.fiscalYearField=app.view.createField(fieldSettings);$el.html(this.fiscalYearField.el);this.fiscalYearField.render();}}},updateFieldMetadata:function(fieldMeta){fieldMeta.startYear=this.tpStartDate.year();return fieldMeta;},removeFiscalYearField:function(){this.model.set({timeperiod_fiscal_year:null});this.fiscalYearField.dispose();this.fiscalYearField=null;this.$('#timeperiod_start_date_subfield').html('')},updateTitle:function(){var tplVars={title:this.titleViewNameTitle,message:this.titleMessage,selectedValues:this.titleSelectedValues,viewName:'forecastsConfigTimeperiods'};this.$('#'+this.name+'Title').html(this.toggleTitleTpl(tplVars));},_renderField:function(field){field=this._setUpTimeperiodConfigField(field);if(this.isForecastSetup){field.options.def.view='detail';}else if(field.name=='timeperiod_start_date'){field.options.def.click_to_edit=true;}
this._super('_renderField',[field]);if(field.name=='timeperiod_start_date'){if(this.isForecastSetup){var year=this.model.get('timeperiod_start_date').substring(0,4),str,$el;if(this.model.get('timeperiod_fiscal_year')==='next_year'){year++;}
str=app.lang.get('LBL_FISCAL_YEAR','Forecasts')+': '+year;$el=this.$('#timeperiod_start_date_sublabel');if($el){$el.html(str);}}else{this.tpStartDate=app.date(this.model.get('timeperiod_start_date'));this.checkFiscalYearField();}}},_render:function(){this._super('_render');this.$el.addClass('accordion-group');this.updateTitle();},_setUpTimeperiodConfigField:function(field){switch(field.name){case"timeperiod_shown_forward":case"timeperiod_shown_backward":return this._setUpTimeperiodShowField(field);case"timeperiod_interval":return this._setUpTimeperiodIntervalBind(field);default:return field;}},_setUpTimeperiodShowField:function(field){field.events=_.extend({"change input":"_updateSelection"},field.events);field.bindDomChange=function(){};field._updateSelection=function(event){var value=$(event.currentTarget).val();this.def.value=value;this.model.set(this.name,value);};this.model.set(field.name,this.model.get(field.name).toString(),{silent:true});field.def.value=this.model.get(field.name)||1;return field;},_setUpTimeperiodIntervalBind:function(field){field.def.value=this.model.get(field.name);field.events=_.extend({"change input":"_updateIntervals"},field.events);field.bindDomChange=function(){};if(typeof(field.def.options)=='string'){field.def.options=app.lang.getAppListStrings(field.def.options);}
field._updateIntervals=function(event){var selected_interval=$(event.currentTarget).val();this.def.value=selected_interval;this.model.set(this.name,selected_interval);this.model.set('timeperiod_leaf_interval',selected_interval=='Annual'?'Quarter':'Month');}
return field;}})