<?php
/* File autogenerated by SugarCRM in ActivitesRelationship.php / buildSidecarDashletMeta */

$coreDefs = MetaDataFiles::loadSingleClientMetadata('view','attachments');
$coreDefs['dashlets'][0]['filter']['module'] = array('con_Contractors');
$coreDefs['dashlets'][0]['config']['link'] = 'con_contractors_activities_1_notes';
$coreDefs['dashlets'][0]['preview']['link'] = 'con_contractors_activities_1_notes';
$viewdefs['con_Contractors']['base']['view']['attachments'] = $coreDefs;
