/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({extendsFrom:'FieldsetField',fields:null,dropdownFields:null,actionDropDownTag:'[data-toggle=dropdown]',selectDropdownTag:'[data-toggle=dropdownmenu]',events:{'click [data-toggle=dropdown]':'renderDropdown','mousedown [data-toggle=dropdownmenu]':'renderDropdown'},plugins:['Tooltip'],showNoData:false,initialize:function(options){this._super('initialize',[options]);this.dropdownFields=[];var actiondropdownField=app.view._getController({type:'field',name:'actiondropdown'});this.setPlaceholder=_.throttle(actiondropdownField.prototype.setPlaceholder,100);app.shortcuts.register('Dropdown:More','m',function(){var $primaryDropdown=this.$('.btn-primary[data-toggle=dropdown]');if($primaryDropdown.is(':visible')&&!$primaryDropdown.hasClass('disabled')){$primaryDropdown.click();}},this);},renderDropdown:function(){if(_.isEmpty(this.dropdownFields)||this.isDisabled()){return;}
_.each(this.dropdownFields,function(field){this.view.fields[field.sfId]=field;field.setElement(this.$('span[sfuuid="'+field.sfId+'"]'));if(this.def['switch_on_click']&&!this.def['no_default_action']){field.$el.on('click.'+this.cid,_.bind(this.switchButton,this));}
field.render();},this);this.dropdownFields=null;if(!this.def['switch_on_click']||this.def['no_default_action']){return;}
var firstField=_.first(this.fields);firstField.$el.on('click.'+this.cid,_.bind(this.switchButton,this));app.accessibility.run(firstField.$el,'click');},switchButton:function(evt){var sfId=parseInt(this.$(evt.currentTarget).attr('sfuuid'),10),index=-1;_.some(this.fields,function(field,idx){if(field.sfId===sfId){index=idx;return true;}
return false;},this);if(index<=0){return;}
var firstField=this.fields.shift(),selectedField=this.fields.splice(index-1,1,firstField).pop();this.fields.splice(0,0,selectedField);this.setPlaceholder();},getPlaceholder:function(){if(this.options.viewName==='list-header')return app.view.Field.prototype.getPlaceholder.call(this);var caretCss='btn dropdown-toggle';if(this.def['no_default_action']){caretCss+=' btn-invisible';}else if(this.def['primary']){caretCss+=' btn-primary';}
var cssClass=[],container='',caretIcon=this.def['icon']?this.def['icon']:'icon-caret-down',caret='<a track="click:actiondropdown" class="'+caretCss+'" data-toggle="dropdown" href="javascript:void(0);" data-placement="bottom" rel="tooltip" title="'+app.lang.get('LBL_LISTVIEW_ACTIONS')+'">'+'<span class="'+caretIcon+'"></span>'+'</a>',dropdown='<ul data-menu="dropdown" class="dropdown-menu" role="menu">';var index=this.def['no_default_action']?1:0;_.each(this.def.buttons,function(fieldDef){var field=app.view.createField({def:fieldDef,view:this.view,viewName:this.options.viewName,model:this.model});this.fields.push(field);field.on('show hide',this.setPlaceholder,this);field.parent=this;if(fieldDef.type==='divider'){return;}
if(index==0){container+=field.getPlaceholder();}else{delete this.view.fields[field.sfId];this.dropdownFields.push(field);if(index==1){cssClass.push('actions','btn-group');container+=caret;container+=dropdown;}
container+='<li>'+field.getPlaceholder()+'</li>';}
index++;},this);var cssName=cssClass.join(' '),placeholder='<span sfuuid="'+this.sfId+'" class="'+cssName+'">'+container;placeholder+=(_.size(this.def.buttons)>0)?'</ul></span>':'</span>';return new Handlebars.SafeString(placeholder);},_render:function(){this._super('_render');this.setPlaceholder();this._updateCaret();},_updateCaret:function(){if(_.isEmpty(this.dropdownFields)){return;}
var caretEnabled=_.some(this.dropdownFields,function(field){if(field.hasAccess()){if(field.def.css_class.indexOf('disabled')>-1){return false;}else if(field.isDisabled()){return false;}else{return true;}}
return false;});if(!caretEnabled){this.$('.icon-caret-down').closest('a').addClass('disabled');}},setPlaceholder:function(){if(this.disposed){return;}
var index=this.def['no_default_action']?1:0,visibleEl=document.createDocumentFragment(),hiddenEl=document.createDocumentFragment();_.each(this.fields,function(field){var cssClass=_.unique(field.def.css_class?field.def.css_class.split(' '):[]),fieldPlaceholder=this.$('span[sfuuid="'+field.sfId+'"]');if(field.type==='divider'){if(index<=1){return;}
var dividerEl=document.createElement('li');dividerEl.className='divider';visibleEl.appendChild(dividerEl);return;}
if(field.isVisible()&&field.hasAccess()){cssClass=_.without(cssClass,'hide');fieldPlaceholder.toggleClass('hide',false);if(index==0){if(field.def.icon&&field.closestComponent('subpanel')){field.setMode('small');}
cssClass.push('btn');field.getFieldElement().addClass('btn');if(this.def.primary){cssClass.push('btn-primary');field.getFieldElement().addClass('btn-primary');}
this.$el.prepend(fieldPlaceholder);}else{if(field._previousAction){field.setMode(field._previousAction);}
cssClass=_.without(cssClass,'btn','btn-primary');field.getFieldElement().removeClass('btn btn-primary');var dropdownEl=document.createElement('li');dropdownEl.appendChild(fieldPlaceholder.get(0));visibleEl.appendChild(dropdownEl);}
index++;}else{cssClass.push('hide');fieldPlaceholder.toggleClass('hide',true);hiddenEl.appendChild(fieldPlaceholder.get(0));}
cssClass=_.unique(cssClass);field.def.css_class=cssClass.join(' ');},this);if(index<=1){this.$(this.actionDropDownTag).hide();this.$el.removeClass('btn-group');}else{this.$(this.actionDropDownTag).show();this.$el.addClass('btn-group');}
this.$('[data-menu=dropdown]').children('li').remove();this.$('[data-menu=dropdown]').append(visibleEl);this.$el.append(hiddenEl);var firstButton=_.first(this.fields);if(firstButton&&!firstButton.isVisible()){this.renderDropdown();}},setDisabled:function(disable){this._super('setDisabled',[disable]);disable=_.isUndefined(disable)?true:disable;if(disable){this.$(this.actionDropDownTag).addClass('disabled');}else{this.$(this.actionDropDownTag).removeClass('disabled');}},_dispose:function(){_.each(this.fields,function(field){field.$el.off('click.'+this.cid);field.off('show hide',this.setPlaceholder,this);},this);this.dropdownFields=null;this._super('_dispose');},isVisible:function(){return!this.getFieldElement().is(':hidden');},setMode:function(mode){this._super('setMode',[mode]);_.each(this.fields,function(field,index){if(index===0&&mode==='list'&&field.def.icon&&field.closestComponent('subpanel')){field.setMode('small');}else{field.setMode(mode);}},this);}})