<?php
/* File autogenerated by SugarCRM in ActivitesRelationship.php / buildSidecarDashletMeta */

$coreDefs = MetaDataFiles::loadSingleClientMetadata('view','active-tasks');
$coreDefs['dashlets'][0]['filter']['module'] = array('jbs_Jobs');
$coreDefs['custom_toolbar']['buttons'][0]['buttons'][0]['params']['link'] = 'jbs_jobs_activities_1_tasks';
$coreDefs['tabs'][0]['link'] = 'jbs_jobs_activities_1_tasks';
$coreDefs['tabs'][1]['link'] = 'jbs_jobs_activities_1_tasks';
$viewdefs['jbs_Jobs']['base']['view']['active-tasks'] = $coreDefs;
