/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({collapseDivId:'forecast-config-accordion',timeperiodsTitle:'',timeperiodsText:'',scenariosTitle:'',scenariosText:'',rangesTitle:'',rangesText:'',forecastByTitle:'',forecastByText:'',wkstColumnsTitle:'',wkstColumnsText:'',selectedPanel:'',events:{'click .accordion-toggle':'onAccordionToggleClicked'},initialize:function(options){app.view.Layout.prototype.initialize.call(this,options);var appLang=app.lang,forecastBy=app.metadata.getModule('Forecasts','config').forecast_by,forecastByLabels={forecastByModule:appLang.getAppListStrings('moduleList')[forecastBy],forecastByModuleSingular:appLang.getAppListStrings('moduleListSingular')[forecastBy]};this.timeperiodsTitle=appLang.get('LBL_FORECASTS_CONFIG_TITLE_TIMEPERIODS','Forecasts');this.timeperiodsText=appLang.get('LBL_FORECASTS_CONFIG_HELP_TIMEPERIODS','Forecasts');this.scenariosTitle=appLang.get('LBL_FORECASTS_CONFIG_TITLE_SCENARIOS','Forecasts');this.scenariosText=appLang.get('LBL_FORECASTS_CONFIG_HELP_SCENARIOS','Forecasts',forecastByLabels);this.rangesTitle=appLang.get('LBL_FORECASTS_CONFIG_TITLE_RANGES','Forecasts');this.rangesText=appLang.get('LBL_FORECASTS_CONFIG_HELP_RANGES','Forecasts',forecastByLabels);this.forecastByTitle=appLang.get('LBL_FORECASTS_CONFIG_HOWTO_TITLE_FORECAST_BY','Forecasts');this.forecastByText=appLang.get('LBL_FORECASTS_CONFIG_HELP_FORECAST_BY','Forecasts');this.wkstColumnsTitle=appLang.get('LBL_FORECASTS_CONFIG_TITLE_WORKSHEET_COLUMNS','Forecasts');this.wkstColumnsText=appLang.get('LBL_FORECASTS_CONFIG_HELP_WORKSHEET_COLUMNS','Forecasts');if(this.context.get('model').get('is_setup')==0){this.context.get('model').set({first_time:1});}},_render:function(){app.view.Layout.prototype._render.call(this);this.$el.addClass('accordion');this.$el.attr('id',this.collapseDivId);this.$('.collapse').collapse({toggle:false,parent:'#'+this.collapseDivId});this.selectPanel(_.first(this.meta.components).view);},selectPanel:function(panelName){this.selectedPanel=panelName;this.$el.find('#'+panelName+'Collapse').collapse('show');this.onAccordionToggleClicked();},onAccordionToggleClicked:function(evt){var helpId=(evt)?$(evt.currentTarget).data('help-id'):this.selectedPanel,data={};switch(helpId){case'forecastsConfigTimeperiods':data.title=this.timeperiodsTitle;data.text=this.timeperiodsText;break;case'forecastsConfigScenarios':data.title=this.scenariosTitle;data.text=this.scenariosText;break;case'forecastsConfigRanges':data.title=this.rangesTitle;data.text=this.rangesText;break;case'forecastsConfigForecastBy':data.title=this.forecastByTitle;data.text=this.forecastByText;break;case'forecastsConfigWorksheetColumns':data.title=this.wkstColumnsTitle;data.text=this.wkstColumnsText;break;}
this.context.set({howtoData:data});}})